services:
  webserver:
    image: caddy:2.9.1-alpine
    container_name: caddy1
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /Users/garvit/Desktop/CCC/frontend:/app
    ports:
      - "80:80"
